/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HubspotFormReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hubspotForm";
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & ExampleSection)
  | ({
      _key: string;
    } & HubspotFormReference)
>;

export type Copy = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ExampleSection = {
  _type: "exampleSection";
  orientation?: "imageLeft" | "imageRight";
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  copy?: Copy;
};

export type HubspotForm = {
  _id: string;
  _type: "hubspotForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  formId: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  homePage: PageReference;
  notFoundPage: PageReference;
  googleTagManagerId?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  metaTitle: string;
  metaDescription?: string;
  noIndex?: boolean;
  noFollow?: boolean;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: PageBuilder;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | HubspotFormReference
  | PageBuilder
  | Copy
  | SanityImageAssetReference
  | ExampleSection
  | HubspotForm
  | PageReference
  | SiteSettings
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../website/src/sanity/queries/pages.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[    _type == "page" &&    defined(slug.current) &&    slug.current != *[_id == "siteSettings"][0].homePage->slug.current  ]{ "slug": slug.current }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../website/src/sanity/queries/pages.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "siteSettings"][0]{    homePage->{      ...,      content[]{        ...,        _type == "reference" => @->      }    }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      homePage: null;
    }
  | {
      homePage: {
        _id: string;
        _type: "page";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        slug: Slug;
        metaTitle: string;
        metaDescription?: string;
        noIndex?: boolean;
        noFollow?: boolean;
        mainImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        content: Array<
          | {
              _key: string;
              _ref: string;
              _type: "hubspotForm";
              _weak?: boolean;
              _id: string;
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              title: string;
              formId: string;
            }
          | {
              _key: string;
              _type: "exampleSection";
              orientation?: "imageLeft" | "imageRight";
              title?: string;
              image?: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              copy?: Copy;
            }
        > | null;
      };
    }
  | null;

// Source: ../website/src/sanity/queries/pages.ts
// Variable: HOME_PAGE_METADATA_QUERY
// Query: *[_id == "siteSettings"][0]{    homePage->{      metaTitle,      metaDescription,      noIndex,      noFollow,    }  }
export type HOME_PAGE_METADATA_QUERY_RESULT =
  | {
      homePage: null;
    }
  | {
      homePage: {
        metaTitle: string;
        metaDescription: string | null;
        noIndex: boolean | null;
        noFollow: boolean | null;
      };
    }
  | null;

// Source: ../website/src/sanity/queries/pages.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    ...,    content[]{      ...,      _type == "reference" => @->    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  metaTitle: string;
  metaDescription?: string;
  noIndex?: boolean;
  noFollow?: boolean;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content: Array<
    | {
        _key: string;
        _ref: string;
        _type: "hubspotForm";
        _weak?: boolean;
        _id: string;
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        formId: string;
      }
    | {
        _key: string;
        _type: "exampleSection";
        orientation?: "imageLeft" | "imageRight";
        title?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        copy?: Copy;
      }
  > | null;
} | null;

// Source: ../website/src/sanity/queries/pages.ts
// Variable: PAGE_METADATA_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    slug,    metaTitle,    metaDescription,    noIndex,    noFollow,  }
export type PAGE_METADATA_QUERY_RESULT = {
  slug: Slug;
  metaTitle: string;
  metaDescription: string | null;
  noIndex: boolean | null;
  noFollow: boolean | null;
} | null;

// Source: ../website/src/sanity/queries/pages.ts
// Variable: NOT_FOUND_PAGE_QUERY
// Query: *[_id == "siteSettings"][0].notFoundPage->{    ...,    content[]{      ...,      _type == "reference" => @->    }  }
export type NOT_FOUND_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  metaTitle: string;
  metaDescription?: string;
  noIndex?: boolean;
  noFollow?: boolean;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content: Array<
    | {
        _key: string;
        _ref: string;
        _type: "hubspotForm";
        _weak?: boolean;
        _id: string;
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        formId: string;
      }
    | {
        _key: string;
        _type: "exampleSection";
        orientation?: "imageLeft" | "imageRight";
        title?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        copy?: Copy;
      }
  > | null;
} | null;

// Source: ../website/src/sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[    _type == "siteSettings"    && _id == "siteSettings"  ][0]{    title,    googleTagManagerId  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: null;
  googleTagManagerId: string | null;
} | null;

// Source: ../website/src/sanity/queries/sitemap.ts
// Variable: SITEMAP_QUERY
// Query: [    ...  *[    _type == "siteSettings" &&    defined(homePage->_id)  ][0...1]{    "slug": "",    "_updatedAt": homePage->_updatedAt  },    ...  *[    _type == "page" &&    _id != *[_type == "siteSettings"][0].homePage._ref  ]    {      "slug": slug.current,      _updatedAt    }  ]
export type SITEMAP_QUERY_RESULT = Array<
  | {
      slug: "";
      _updatedAt: string;
    }
  | {
      slug: string;
      _updatedAt: string;
    }
>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "page" &&\n    defined(slug.current) &&\n    slug.current != *[_id == "siteSettings"][0].homePage->slug.current\n  ]{ "slug": slug.current }\n': PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0]{\n    homePage->{\n      ...,\n      content[]{\n        ...,\n        _type == "reference" => @->\n      }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0]{\n    homePage->{\n      metaTitle,\n      metaDescription,\n      noIndex,\n      noFollow,\n    }\n  }\n': HOME_PAGE_METADATA_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    ...,\n    content[]{\n      ...,\n      _type == "reference" => @->\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    slug,\n    metaTitle,\n    metaDescription,\n    noIndex,\n    noFollow,\n  }\n': PAGE_METADATA_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0].notFoundPage->{\n    ...,\n    content[]{\n      ...,\n      _type == "reference" => @->\n    }\n  }\n': NOT_FOUND_PAGE_QUERY_RESULT;
    '\n  *[\n    _type == "siteSettings"\n    && _id == "siteSettings"\n  ][0]{\n    title,\n    googleTagManagerId\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '[\n    ...\n  *[\n    _type == "siteSettings" &&\n    defined(homePage->_id)\n  ][0...1]{\n    "slug": "",\n    "_updatedAt": homePage->_updatedAt\n  }\n,\n    ...\n  *[\n    _type == "page" &&\n    _id != *[_type == "siteSettings"][0].homePage._ref\n  ]\n\n    {\n      "slug": slug.current,\n      _updatedAt\n    }\n  ]': SITEMAP_QUERY_RESULT;
  }
}
